### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by XVilka** [ujamjar/hardcaml-yosys#5]
Change from https://github.com/ujamjar/hardcaml-yosys/issues/4

There are still many changes since the last release at http://opam.ocaml.org/packages/hardcaml-yosys/, would be awesome to have a new one.

**Comment by XVilka** [comment]
Seems problems from https://github.com/ujamjar/hardcaml-yosys/pull/6 should be solved first

**Comment by andrewray** [comment]
There will not be a new release from this repo, but rather a new release with the new hardcaml version coming from Jane Street,.

I will fix opam to reflect this.
